//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorDetails.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CalculatorDetail
    {
        public int id { get; set; }
        public int number1 { get; set; }
        public int number2 { get; set; }
        public string typeOfOperation { get; set; }
        public int result { get; set; }
    }
}
